chromedriver:
  image: robcherry/docker-chromedriver:latest
  ports:
    - '4444'
  cap_add:
    - SYS_ADMIN
  volumes:
    - ".:/var/www:cached"
  environment:
    CHROMEDRIVER_WHITELISTED_IPS: ''

# create links to these services
links:
  - test


