# the service
elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
  volumes:
    - db-data:/var/lib/elasticsearch/data
  ports:
    - '9200:9200'
  environment:
    xpack.security.enabled: 'false'

# create links to these services
links:
  - dev

# post install instructions
instructions: elasticsearch exposes 9200 to the public